
spring:
  application:
    name: article-service

server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
     token-info-uri: http://localhost:8087/oauth/check_token
    client:
     client-id: client
     client-secret: secret        